#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path: /login_check

doctor_controllers:
  resource: ../src/Controller/Doctor
  type: annotation
  prefix: /doctor